### ISSUE TITLE
TO-DO List

### ISSUE THREAD

**Issue by Fr0sT-Brutal** [Fr0sT-Brutal/Delphi_OSMMap#12]
Main TO-DO list

### Internal

- [ ] Support another tile sizes.
- [ ] Load KML files [backlog; PRs welcome]

### Download

- [ ] Speedup tile download process: don't request tiles that are quickly scrolled by (#9)
- [x] Add ability to use another tile providers (#11)
- [ ] HTTPS support for FPC ~/Delphi RTL, Synapse~
- [x] System proxy for FPC RTL, Synapse on Linux (get env var http_proxy)
- [x] reuse connection for requests (?)

### TilesProvider

- [x] implement {x}, {y}, ... substitutions to URL
- [ ] add new providers
  - Yandex.com maps: unlikely. No free tile API. Free API uses geo coords which is too messy to convert to tiles.
  - Bing maps: maybe. Requires API key and no clear explanation regarding prices.
  - Mapbox (https://docs.mapbox.com/api/maps/static-tiles/): maybe. Requires API key
  - Maptiler (https://docs.maptiler.com/cloud/api/tiles/): maybe. Requires API key
  - More OSM (https://wiki.openstreetmap.org/wiki/Raster_tile_providers): likely
- [ ] add style name property (map, sat, mixed, etc). Or just take it from properties list

### UI

- [ ] Join mapmarks to mark with count number if they're too close - need to know how to quickly find mapmarks nearby
- [x] Mapmark click event
- [x] Draw lines (#3)
- [ ] Draw filled polygons - add them just like tracks with all visibility/layer props, draw with transparency [backlog; PRs welcome]
- [ ] Draw additional layers

### Other

- [ ] Meta: Delphinus, Lazarus PM support
